"""added gender column

Revision ID: 60cac6d6c8ea
Revises: 
Create Date: 2020-10-09 02:52:49.875093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cac6d6c8ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UsersTable', sa.Column('gender', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UsersTable', 'gender')
    # ### end Alembic commands ###
